ALTER TABLE "tbl_mps_detail"
  ADD COLUMN IF NOT EXISTS "buffer_overridden" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "production_percent" DOUBLE PRECISION NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS "production_overridden" BOOLEAN NOT NULL DEFAULT FALSE;
