const router = require("express").Router();
const ctrl = require("../../controllers/engineering/RoutingController");
const { authorize } = require("../../middleware/auth");
const { logger } = require("../../middleware/logger");
router.get("/work-centers", authorize("machines", "read"), ctrl.listWorkCenters);
router.get("/work-centers/:key", authorize("machines", "read"), ctrl.getWorkCenter);
router.post("/work-centers", authorize("machines", "create"), logger("work-center", "create"), ctrl.createWorkCenter);
router.get("/routings", authorize("mbom", "read"), ctrl.listRoutings);
router.get("/routings/:key", authorize("mbom", "read"), ctrl.getRouting);
router.post("/routings", authorize("mbom", "create"), logger("routing", "create"), ctrl.createRouting);
router.patch("/mbom-processes/:id/link", authorize("mbom", "update"), logger("mbom-process", "link-routing"), ctrl.linkMbomProcess);
module.exports = router;
