ALTER TABLE "tbl_mrp_run"
  ADD COLUMN IF NOT EXISTS "so_demand_consumed_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "so_demand_impacted_lines" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "netting_summary" JSONB;

ALTER TABLE "tbl_mrp_requirement"
  ADD COLUMN IF NOT EXISTS "forecast_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "so_consumed_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "effective_demand_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "consumption_sources" JSONB;
