ALTER TABLE "tbl_mrp_requirement"
ADD COLUMN "buffer_base_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "buffer_percent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "buffer_qty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "buffer_overridden" BOOLEAN NOT NULL DEFAULT false;
