"use strict";
const { buildCapacitySnapshot } = require("../../planning/capacityPlanningService");
const n = (v) => Number.isFinite(Number(v)) ? Number(v) : 0;
const src = (type, id, label, href) => ({ entityType: type, entityId: String(id), label: String(label), href });
function buildCapacityRisks(snapshot = {}) {
  const risks = [];
  for (const machine of snapshot.machines || []) for (const [date, cell] of Object.entries(machine.cells || {})) {
    const available = n(cell.availableMinutes), load = n(cell.loadMinutes || cell.firmMinutes || cell.minutes), overload = Math.max(load - available, 0), utilization = available > 0 ? Math.round(load / available * 10000) / 100 : load > 0 ? 999 : 0;
    if (overload <= 0 && utilization < 85) continue;
    for (const item of cell.items?.length ? cell.items : [{}]) risks.push({ riskCode: overload > 0 ? "CAPACITY_OVERLOAD" : "HIGH_LOAD", severity: overload > 0 ? "OVERLOAD" : "WARNING", machineId: machine.id, machineCode: machine.machineCode, workCenterId: machine.workCenterId || machine.lineCode || null, date, utilization, overloadMinutes: Math.round(overload * 100) / 100, sourceAllocationId: item.allocationId || null, mbomProcessId: item.mbomProcessId || null, processCode: item.processCode || null, partCode: item.partCode || null, fgRequiredDate: item.fgRequiredDate || null, deliveryPhaseId: item.deliveryPhaseId || null, rootCause: overload > 0 ? "LOAD_EXCEEDS_EFFECTIVE_CAPACITY" : "LOAD_NEAR_CAPACITY", allowedAlternatives: item.allowedAlternatives || [], sources: [src("CAPACITY_CELL", `${machine.id}:${date}`, `${machine.machineCode} · ${date}`, `/modules/planning-ppic/capacity-planning?machineId=${encodeURIComponent(machine.id)}&date=${date}`), ...(item.deliveryPhaseId ? [src("FG_DELIVERY_PHASE", item.deliveryPhaseId, item.partCode || "FG", `/modules/planning-ppic/demand-planning/delivery-workbench?deliveryTargetId=${encodeURIComponent(item.deliveryPhaseId)}`)] : [])] });
  }
  for (const item of snapshot.unscheduled || snapshot.attentionItems || []) risks.push({ riskCode: item.riskCode || item.reasonCode || "UNSCHEDULED_ROUTE", severity: "WARNING", machineId: item.machineId || null, machineCode: item.machineCode || null, workCenterId: item.workCenterId || null, date: item.date || null, utilization: 0, overloadMinutes: 0, sourceAllocationId: item.allocationId || null, mbomProcessId: item.mbomProcessId || null, processCode: item.processCode || null, partCode: item.partCode || null, fgRequiredDate: item.fgRequiredDate || null, deliveryPhaseId: item.deliveryPhaseId || null, rootCause: item.rootCause || item.riskCode || "UNSCHEDULED_ROUTE", allowedAlternatives: item.allowedAlternatives || [], sources: [] });
  return risks.slice(0, 100);
}
function createCapacityCapabilityDefinitions({ buildSnapshot = buildCapacitySnapshot } = {}) {
  const permission = { moduleCode: "planning-ppic", pageCode: "capacity-planning", resourceCode: "capacityPlanning", action: "read" };
  const load = async ({ prisma, input }, presetId = input.presetId) => buildSnapshot(prisma, { planNumber: input.planNumber, startDate: `${input.month}-01`, endDate: `${input.month}-31`, planningMode: input.planningMode || "PRODUCTION", presetId, manualAllocation: true });
  const risks = async (ctx) => { const items = buildCapacityRisks(await load(ctx)); return { items, sources: items.flatMap((row) => row.sources).slice(0, 100) }; };
  const props = { month: { type: "string", pattern: "^[0-9]{4}-[0-9]{2}$" }, planNumber: { type: "string" }, planningMode: { type: "string" }, presetId: { type: "string" }, machineId: { type: "string" }, date: { type: "string", format: "date" }, riskCode: { type: "string" } };
  const common = { type: "object", additionalProperties: false, required: ["month"], properties: props };
  return [
    { code: "ppic.get_capacity_risk", operationClass: "ANALYZE", permission, maxRows: 100, fieldAllowlist: ["items", "sources"], inputSchema: common, outputSchema: { type: "object" }, execute: risks },
    { code: "ppic.compare_capacity_presets", operationClass: "ANALYZE", permission, maxRows: 100, fieldAllowlist: ["left", "right", "delta", "sources"], inputSchema: { ...common, required: ["month", "presetA", "presetB"], properties: { ...props, presetA: { type: "string" }, presetB: { type: "string" } } }, outputSchema: { type: "object" }, execute: async (ctx) => { const left = buildCapacityRisks(await load(ctx, ctx.input.presetA)); const right = buildCapacityRisks(await load(ctx, ctx.input.presetB)); return { left, right, delta: { riskCount: right.length - left.length }, sources: [] }; } },
    { code: "ppic.explain_capacity_blocker", operationClass: "ANALYZE", permission, maxRows: 100, fieldAllowlist: ["item", "sources"], inputSchema: common, outputSchema: { type: "object" }, execute: async (ctx) => { const result = await risks(ctx); const item = result.items.find((row) => (!ctx.input.machineId || row.machineId === ctx.input.machineId) && (!ctx.input.date || row.date === ctx.input.date) && (!ctx.input.riskCode || row.riskCode === ctx.input.riskCode)) || null; return { item, sources: item?.sources || [] }; } },
    { code: "ppic.create_capacity_simulation_draft", operationClass: "DRAFT", permission: { ...permission, action: "update" }, maxRows: 100, fieldAllowlist: ["id", "status", "draftType", "payload", "sourceRefs", "expiresAt"], inputSchema: { type: "object", additionalProperties: false, required: ["conversationId", "requestId", "month", "name", "basePresetId", "dailyOverrides", "allocationChanges", "vendorDateChanges", "explanation"], properties: { conversationId: { type: "string" }, requestId: { type: "string" }, month: { type: "string" }, name: { type: "string" }, basePresetId: { type: ["string", "null"] }, dailyOverrides: { type: "array", maxItems: 31 }, allocationChanges: { type: "array", maxItems: 100 }, vendorDateChanges: { type: "array", maxItems: 100 }, explanation: { type: "string" } } }, outputSchema: { type: "object" }, execute: async ({ prisma, input, user }) => prisma.aiDraft.create({ data: { conversationId: input.conversationId, requestId: input.requestId, userId: String(user.id), moduleCode: "planning-ppic", pageCode: "capacity-planning", draftType: "CAPACITY_SIMULATION", generationSource: "AI_GENERATED", status: "WAITING_CONFIRMATION", payload: { month: input.month, name: input.name, basePresetId: input.basePresetId, dailyOverrides: input.dailyOverrides, allocationChanges: input.allocationChanges, vendorDateChanges: input.vendorDateChanges, explanation: input.explanation }, sourceRefs: [], validationSummary: { valid: true, issues: [] }, expiresAt: new Date(Date.now() + 2 * 86400000) } }) },
  ];
}
function registerCapacityCapabilities(registry) { for (const definition of createCapacityCapabilityDefinitions()) if (!registry.has(definition.code)) registry.register(definition); return registry; }
module.exports = { buildCapacityRisks, createCapacityCapabilityDefinitions, registerCapacityCapabilities };
