ALTER TABLE "tbl_work_order"
ADD COLUMN IF NOT EXISTS "machine_costing_rate" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "machine_rate_type" TEXT,
ADD COLUMN IF NOT EXISTS "machine_currency" TEXT,
ADD COLUMN IF NOT EXISTS "planned_process_cost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "actual_process_cost" DOUBLE PRECISION NOT NULL DEFAULT 0;
