const router = require("express").Router();
const ctrl = require("../../controllers/planning/MPSController");
const rccp = require("../../controllers/planning/RccpController");
const { authorize } = require("../../middleware/auth");
const { logger } = require("../../middleware/logger");
const { approvalGate } = require("../../services/approvalRuleService");
const { guardMonthBody, guardMps } = require("../../middleware/planningPeriodGuard");

const mpsApproval = approvalGate({ moduleCode: "planning-ppic", pageCode: "master-production-schedule", actionCode: "approve", documentType: "MPS", param: "mpsNumber", model: "mPS", lookupField: "mpsNumber", numberField: "mpsNumber" });

router.get("/generate-number", authorize("mps", "create"), ctrl.generateNumber);
router.get("/monthly-summary", authorize("mps", "read"), ctrl.monthlySummary);
router.get("/workbench", authorize("mps", "read"), ctrl.workbench);
router.get("/workbench/lines/:lineId/feasibility", authorize("mps", "read"), ctrl.workbenchFeasibility);
router.get("/mbom-revision-options", authorize("mps", "read"), ctrl.mbomRevisionOptions);
router.post("/from-forecast", authorize("mps", "create"), logger("mps", "create-from-forecast"), ctrl.createFromForecast);
router.post("/monthly-sync", authorize("mps", "create"), guardMonthBody, logger("mps", "sync-monthly-demand"), ctrl.syncMonthly);
router.post("/recalculate", authorize("mps", "update"), guardMonthBody, logger("mps", "recalculate-locked-mps"), ctrl.recalculateLocked);
router.post("/baseline/preview", authorize("mps", "read"), ctrl.previewBaseline);
router.post("/baseline/generate", authorize("mps", "create"), logger("mps", "generate-baseline"), ctrl.generateBaseline);
router.post("/delta/preview", authorize("mps", "read"), ctrl.previewDelta);
router.post("/delta/generate", authorize("mps", "create"), logger("mps", "generate-delta"), ctrl.generateDelta);
router.post("/production-cut/preview", authorize("mps", "read"), ctrl.previewProductionCut);
router.post("/production-cut", authorize("mps", "update"), logger("mps", "create-production-cut"), ctrl.createProductionCut);
router.patch("/production-cut/:adjustmentNumber/approve", authorize("mps", "approve"), logger("mps", "approve-production-cut"), ctrl.approveProductionCut);
router.get("/:mpsNumber/readiness", authorize("mps", "read"), ctrl.readiness);
router.post("/:mpsNumber/delivery-phases", authorize("mps", "update"), guardMps, logger("mps", "create-delivery-phase", { modelName: "MPS", paramKey: "mpsNumber", whereKey: "mpsNumber" }), ctrl.createDeliveryPhase);
router.patch("/:mpsNumber/delivery-phases/:phaseId/remove", authorize("mps", "update"), guardMps, logger("mps", "remove-delivery-phase", { modelName: "MPS", paramKey: "mpsNumber", whereKey: "mpsNumber" }), ctrl.removeDeliveryPhase);
router.patch("/:mpsNumber/adjustments", authorize("mps", "update"), guardMps, logger("mps", "update-adjustments", { modelName: "MPS", paramKey: "mpsNumber", whereKey: "mpsNumber" }), ctrl.updateAdjustments);
router.get("/:mpsNumber/rccp/latest", authorize("mps", "read"), rccp.latest);
router.get("/rccp/:runId", authorize("mps", "read"), rccp.get);
router.get("/rccp/:runId/timeline", authorize("mps", "read"), rccp.timeline);
router.get("/rccp/:runId/offset-load", authorize("mps", "read"), rccp.offsetLoad);
router.get("/rccp/:runId/recommendations", authorize("mps", "read"), rccp.recommendations);
router.post("/rccp/:runId/recommendations/:recommendationId/apply", authorize("mps", "approve"), logger("mps", "apply-rccp-recommendation"), rccp.applyRecommendation);
router.post("/rccp/:runId/acknowledge", authorize("mps", "approve"), logger("mps", "acknowledge-rccp-warning"), rccp.acknowledge);
router.post("/rccp/:runId/override", authorize("mps", "approve"), logger("mps", "override-rccp-overload"), rccp.override);
router.patch("/:mpsNumber/approve", authorize("mps", "approve"), guardMps, mpsApproval, logger("mps", "approve", { modelName: "MPS", paramKey: "mpsNumber", whereKey: "mpsNumber" }), ctrl.confirm);
router.patch("/:mpsNumber/confirm", authorize("mps", "approve"), guardMps, mpsApproval, logger("mps", "confirm", { modelName: "MPS", paramKey: "mpsNumber", whereKey: "mpsNumber" }), ctrl.confirm);
router.get("/", authorize("mps", "read"), ctrl.list);
router.get("/:mpsNumber", authorize("mps", "read"), ctrl.get);
module.exports = router;
