const router = require("express").Router();
const ctrl = require("../../controllers/planning/MRPController");
const purchaseSuggestionCtrl = require("../../controllers/purchasing/PurchaseSuggestionController");
const { authorize } = require("../../middleware/auth");
const { logger } = require("../../middleware/logger");
const { guardMps, guardMrp } = require("../../middleware/planningPeriodGuard");

router.get("/generate-number", authorize("mrp", "create"), ctrl.generateNumber);
router.get("/general-summary", authorize("mrp", "read"), ctrl.generalSummary);
router.get("/planned-orders", authorize("mrp", "read"), ctrl.listPlannedOrders);
router.get("/planned-orders/:orderNumber", authorize("mrp", "read"), ctrl.getPlannedOrder);
router.get("/net-change/dirty-items", authorize("mrp", "read"), ctrl.listNetChangeDirtyItems);
router.get("/net-change/snapshots/latest", authorize("mrp", "read"), ctrl.getLatestNetChangeSnapshot);
router.get("/net-change/snapshots", authorize("mrp", "read"), ctrl.listNetChangeSnapshots);
router.post("/net-change/run", authorize("mrp", "release"), logger("mrp", "run-net-change"), ctrl.runNetChange);
router.get("/", authorize("mrp", "read"), ctrl.list);
router.post("/delta/run", authorize("mrp", "create"), guardMps, logger("mrp", "run-delta"), ctrl.runDeltaMRP);
router.post("/run", authorize("mrp", "create"), guardMps, logger("mrp", "run"), ctrl.runMRP);
router.patch("/:runNumber/approve", authorize("mrp", "release"), guardMrp, logger("mrp", "approve"), ctrl.approve);
router.get("/:runNumber/audit", authorize("mrp", "read"), ctrl.getAudit);
router.get("/:runNumber/requirements", authorize("mrp", "read"), ctrl.getRequirements);
router.get("/:runNumber/procurement-view", authorize("mrp", "read"), ctrl.procurementView);
router.get("/:runNumber/customer-pegging-view", authorize("mrp", "read"), ctrl.customerPeggingView);
router.patch("/:runNumber/requirements/buffer", authorize("mrp", "update"), guardMrp, logger("mrp", "update-buffer"), ctrl.updateRequirementBuffer);
router.patch("/:runNumber/requirements/order-percent", authorize("mrp", "update"), guardMrp, logger("mrp", "update-order-percent"), ctrl.updateRequirementBuffer);
router.post("/:runNumber/output/purchase-suggestions", authorize("mrp", "release"), guardMrp, logger("mrp", "generate-purchase-suggestions"), purchaseSuggestionCtrl.generate);
router.post("/:runNumber/output/production-plan", authorize("mrp", "release"), guardMrp, logger("mrp", "release-production-plan"), ctrl.createProductionPlanOutput);
router.patch("/:runNumber/planned-orders/procurement", authorize("mrp", "update"), guardMrp, logger("mrp", "update-procurement-proposal"), ctrl.updatePlannedOrderProcurement);
router.get("/:runNumber/planned-orders", authorize("mrp", "read"), ctrl.getPlannedOrders);
router.get("/:runNumber", authorize("mrp", "read"), ctrl.get);
router.delete("/:runNumber", authorize("mrp", "delete"), guardMrp, logger("mrp", "delete", { modelName: "MRPRun", paramKey: "runNumber", whereKey: "runNumber" }), ctrl.remove);
module.exports = router;
